site_name: JW Player Skinning
theme: readthedocs
site_favicon: favicon.ico
pages:
- Introduction: index.md
- Creating Skins: skins_creating.md
- Custom Icons and Fonts: skins_fonts.md
- CSS Reference List: skins_ref.md
- DOM Structure Visual Reference: dom-structure.md
- Example CSS File: skins_example.md
- Design Resources: designer-kit.md

