site_name: JW Player Developer Guide
theme: cyborg
site_favicon: favicon.ico
pages:
  - Home: index.md
  - Customization:
    - Creating Skins: customization/css-skinning/skins_creating.md
    - Custom Icons and Fonts: customization/css-skinning/skins_fonts.md
    - CSS Reference List: customization/css-skinning/skins_reference.md
    - DOM Structure Visual Reference: customization/css-skinning/dom-structure.md
    - Example CSS File: customization/css-skinning/skins_example.md
  - Design Resources: customization/designer-kit.md
  - Beta Program:
    - HLS in HTML5: beta/html5_hls_beta.md
site_dir: developer-guide
