site_name: JW Player JavaScript API Reference
site_favicon: favicon.png
docs_dir: docs
site_dir: javascript-api-reference
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false
site_favicon: favicon.ico
extra:
  singlePage: true
  product: player
nav:
  - v8 Javascript API Reference: index.md
  - v7 Javascript API Reference: jw7/index.md
markdown_extensions:
  - markdown_fenced_code_tabs
