site_name: JW Player Developer Guide
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false
extra:
  product: player
nav:
  - Getting Started:
    - Introduction: index.md
    - Intro to Javascript API: api/javascript_api_introduction.md
    - Using Release Channels: release_notes/release_channels.md
    - Add an HTML5 player to a site: getting-started/add-an-html5-player.md
  - Content:
    - Set up Recommendations: content/set-up-recommendations.md
    - Embed videos with Article Matching: customization/embed-relevant-videos-with-article-matching.md
  - Branding:
    - CSS Skinning Reference: customization/css-skinning/skins_reference.md
    - CSS Skinning Model: customization/css-skinning-model.md
    - Custom Skins: customization/css-skinning/skins_creating.md
    - Custom Icons: customization/css-skinning/custom-icons.md
    - Example CSS File: customization/css-skinning/skins_example.md
    - JW8 Designer Kit: customization/designer-kit.md
  - Behavior:
    - Set the dimensions of a player: behavior/set-the-dimensions-of-a-player.md
  - Advertising:
    - Monetize your content: advertising/monetize-your-content.md
    - Define ad rules: advertising/define-ad-rules.md
    - Enable FreeWheel Ad Manager: advertising/enable-freewheel-ad-manager.md
    - Set up Video Player Bidding: advertising/set-up-video-player-bidding.md
    - Validate your VPB implementation: advertising/validate-your-video-player-bidding-implementation.md
  - Analytics:
    - Track video metrics: analytics/track-video-metrics.md
    - Analytics Integrations: analytics/integrations.md
    - Send events to Adobe Analytics: analytics/send-jw-player-events-to-adobe-analytics.md
  - Troubleshooting:
    - JW Lens overview: troubleshooting/jw-lens-overview.md
    - Troubleshoot analytics discrepancies: analytics/troubleshoot-analytics-discrepancies.md
    - Troubleshoot Video Player Bidding issues: troubleshooting/troubleshoot-video-player-bidding-issues.md
  - Reference:
    - Configuration Reference: customization/configuration-reference.md
    - Ads Errors Reference: advertising/ads_errors_reference.md
    - Errors Reference: api/errors-reference.md
  - JW 7 Developer Guide:
    - JW7 Javascript API: jw7/javascript-api-reference.md
    - JW7 Configuration Reference: jw7/configuration-reference.md
    - JW7 CSS Skinning Reference: jw7/skins_reference.md
    - JW7 CSS Skinning Model: jw7/css-skinning-model.md
    - JW7 Custom Skins: jw7/skins_creating.md
    - JW7 Custom Icons and Fonts: jw7/skins_fonts.md
    - JW7 Example CSS File: jw7/skins_example.md
    - JW7 Designer Kit: jw7/designer-kit.md
    - JW7 Analytics Integrations: jw7/integrations.md

site_dir: developer-guide
markdown_extensions:
   - markdown_fenced_code_tabs
