site_name: JW Player Skinning
theme: readthedocs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
markdown_extensions:
- markdown.extensions.toc:
title: "THIS IS A CUSTOM TOC"
pages:
- Home: index.md
- Creating Skins: skins_creating.md
- Custom Icons and Fonts: skins_fonts.md
- CSS Reference List: skins_ref.md
- Example CSS File: skins_example.md
